version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-php-fpm
    working_dir: /var/www
    volumes:
      - ./app:/var/www
      - ./php/config/php.ini:/etc/php/7.2/cli/php.ini
      - ./php/config/fpm/pool.d/www.conf:/etc/php/7.2/fpm/pool.d/www.conf
      - ./php/config/xdebug.ini:/etc/php/7.2/mods-available/xdebug.ini
      - ./nginx/config:/etc/nginx
    ports:
      - 80:80
